const fs = require("fs");
const { GoogleGenerativeAI } = require("@google/generative-ai");

const genAI = new GoogleGenerativeAI("");

export async function generateModelText(img_path: string) {
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const prompt =
      "The given image is generated by a CNN model which depicts how the tuberculosis prediction were made. Write an answer in points from the perspective such that it is easy for doctors to understand . Also metion how this could be used by a normal person who desent have any idea about Ai and CNN to get the insights from the graph about model ,and give the output in simple text no bold letters no paragraphs nothing.";

    const image = {
      inlineData: {
        data: Buffer.from(
          fs.readFileSync(`src\\app\\lib\\${img_path}`)
        ).toString("base64"),
        mimeType: "image/png",
      },
    };

    const result = await model.generateContent([prompt, image]);
    const response = await result.response;
    const modelExplanation = response.text();
    console.log(modelExplanation);
    return modelExplanation;
  } catch (error) {
    console.error("Error generating model text:", error);
    throw error;
  }
}
