import {Configuration, OpenAIApi} from 'openai-edge'

const config = new Configuration({
    apiKey: process.env.OPENAI_API_KEY
})

const openAi = new OpenAIApi(config)

export async function generateModelText(model_text: string) {
    try {
        const response = await openAi.createChatCompletion({
            model: 'gpt-3.5-turbo',
            messages: [
                {
                    // telling gpt his role
                    role: 'system',
                    content: 'you are a creative and helpful AI assistant capable of generating Explaination for the result of model_text provided to you. Your output will be directly rendered on the application after proof reading'
                },
                {
                    // giving gpt the model_text to generate the explainations
                    role: 'user',
                    content: `we have a ${model_text} algorithm generated image for tuberulosis chest x-ray. Write the technical explainations for results generated by the this model in 3 short points with each point having 10 words only.`
                }
            ] 
        })
        const data = await response.json()
        const modelExplaination = data.choices[0].message.content
        console.log("model_text", model_text)
        console.log(modelExplaination)
        return modelExplaination
    }
    catch(error) {
        console.log(error)
        throw error;
    }

}