import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import cn from "./lib/utils";
import Navbar from "./component/Navbar";
import { Toaster } from "@/components/ui/sonner";
import Provider from "./component/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ExAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light scroll-smooth">
      <Provider>
        <body
          className={cn(
            "min-hscreen font-sans antialised grainy",
            inter.className
          )}
        >
          <Navbar />
          {children}
          <Toaster />
        </body>
      </Provider>
    </html>
  );
}
